version: "1"

session:
  save_root: recordings/cosmos_top_camera_pixel_idm_chunk_policy
  start_paused: true
  record_on_unpause: false

nodes:
  - type: AgentNode
    name: cosmos_top_camera_pixel_idm_policy
    agent_class: robots_realtime.agents.policy_learning.cosmos_top_camera_pixel_idm_chunk_agent:CosmosTopCameraPixelIDMChunkAgent
    agent_kwargs:
      cosmos_url: http://127.0.0.1:8021
      pixel_idm_url: http://127.0.0.1:8022
      prompt:
      source_hz: 10
      command_hz: 30
      cosmos_video_fps: 10
      cosmos_num_frames: 61
      image_key: top_camera
      validate_only:
      array_key: predicted_actions
      request_timeout_s: 900
      num_latent_conditional_frames: 2
      open_video_plan: false
      left_limits_path: robot_configs/yam/xdof_hq/left.yaml
      right_limits_path: robot_configs/yam/xdof_hq/right.yaml
      limit_tolerance: 0.15
      gripper_clamp_tolerance: 0.02
      max_handoff_distance: 0.75
    state_topics:
      left: yam_left/joint_state
      right: yam_right/joint_state
    image_topics:
      top_camera: camera_top/rgb
    loop_mode: fixed_rate
    poll_freq: 30

  - type: RobotNode
    name: yam_left
    robot_config: robot_configs/yam/xdof_hq/left_can_follow.yaml
    cmd_topic: cosmos_top_camera_pixel_idm_policy/left_pos
    poll_freq: 200
    ramp_duration_s: 1.5
    startup_joint_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    startup_duration_s: 2.0

  - type: RobotNode
    name: yam_right
    robot_config: robot_configs/yam/xdof_hq/right_can_follow.yaml
    cmd_topic: cosmos_top_camera_pixel_idm_policy/right_pos
    poll_freq: 200
    ramp_duration_s: 1.5
    startup_joint_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    startup_duration_s: 2.0

  - type: CameraNode
    name: camera_top
    driver: RealSenseCamera
    device_id: "203522250539"
    resolution: HD720
    fps: 30

  - type: ViserMonitorNode
    name: viz
    port: 8080
    viz_freq: 20
    auto_open_browser: true
    fullscreen: true
    up_axis: "+z"
    initial_camera_position: [-0.7, -0.31, 0.3]
    initial_camera_look_at: [0.45, -0.31, 0.3]
    chunk_topic: cosmos_top_camera_pixel_idm_policy/chunk
    n_chunk_frames: 10
    chunk_frame_axes_length: 0.03
    urdfs:
      yam_left:
        path: dependencies/i2rt/i2rt/robot_models/arm/yam/yam.urdf
        state_topic: yam_left/joint_state
        flip_joints: true
        chunk_arm_key: left
        gripper:
          type: linear_4310
          attach_link: link_6
      yam_right:
        path: dependencies/i2rt/i2rt/robot_models/arm/yam/yam.urdf
        state_topic: yam_right/joint_state
        flip_joints: true
        chunk_arm_key: right
        gripper:
          type: linear_4310
          attach_link: link_6
        extrinsic:
          position: [0.0, -0.61, 0.0]
          rotation: [1.0, 0.0, 0.0, 0.0]
    image_topics:
      top: cosmos_top_camera_pixel_idm_policy/image/top_camera
      plan: cosmos_top_camera_pixel_idm_policy/image/cosmos_plan
