_target_: i2rt.robots.motor_chain_robot.MotorChainRobot
motor_chain:
  _target_: i2rt.motor_drivers.dm_driver.DMChainCanInterface
  motor_list:
    - [0x01, "DM4340"]
    - [0x02, "DM4340"]
    - [0x03, "DM4340"]
    - [0x04, "DM4310"]
    - [0x05, "DM4310"]
    - [0x06, "DM4310"]
  motor_offset: [0, 0, 0, 0, 0, 0]
  motor_direction: [1, 1, 1, 1, 1, 1]
  channel: "can_tleader_l"
  motor_chain_name: "yam_leader_left"
  receive_mode:
    _target_: i2rt.motor_drivers.dm_driver.ReceiveMode
    value: "p16"
  get_same_bus_device_driver:
    _callable_: robots_realtime.utils.encoder_utils.get_encoder_chain_for_teaching_handle
xml_path: "dependencies/i2rt/i2rt/robot_models/arm/yam/yam.xml"
gravity_comp_factor: 1.1
kp: [80, 80, 80, 40, 10, 10]
kd: [5, 5, 5, 1.5, 1.5, 1.5]
joint_limits:
  - [-2.768, 3.204]
  - [-0.15, 3.8]
  - [-0.15, 3.815]
  - [-1.721, 1.721]
  - [-1.721, 1.721]
  - [-2.244, 2.244]
